SET IDENTITY_INSERT [dbo].[Collocations] ON
INSERT INTO [dbo].[Collocations] ([Id], [posId], [colPosId], [wordId], [colWordId], [CollocationPattern]) VALUES (1, 1, 2, 1, 5, 1)
INSERT INTO [dbo].[Collocations] ([Id], [posId], [colPosId], [wordId], [colWordId], [CollocationPattern]) VALUES (2, 1, 3, 3, 4, 2)
INSERT INTO [dbo].[Collocations] ([Id], [posId], [colPosId], [wordId], [colWordId], [CollocationPattern]) VALUES (3, 2, 4, 3, 6, 5)
INSERT INTO [dbo].[Collocations] ([Id], [posId], [colPosId], [wordId], [colWordId], [CollocationPattern]) VALUES (4, 2, 4, 3, 7, 5)
INSERT INTO [dbo].[Collocations] ([Id], [posId], [colPosId], [wordId], [colWordId], [CollocationPattern]) VALUES (7, 1, 3, 1, 8, 2)
INSERT INTO [dbo].[Collocations] ([Id], [posId], [colPosId], [wordId], [colWordId], [CollocationPattern]) VALUES (8, 1, 2, 1, 9, 1)
INSERT INTO [dbo].[Collocations] ([Id], [posId], [colPosId], [wordId], [colWordId], [CollocationPattern]) VALUES (9, 1, 2, 1, 10, 1)
INSERT INTO [dbo].[Collocations] ([Id], [posId], [colPosId], [wordId], [colWordId], [CollocationPattern]) VALUES (10, 2, 4, 3, 11, 5)
INSERT INTO [dbo].[Collocations] ([Id], [posId], [colPosId], [wordId], [colWordId], [CollocationPattern]) VALUES (11, 2, 4, 3, 12, 5)
INSERT INTO [dbo].[Collocations] ([Id], [posId], [colPosId], [wordId], [colWordId], [CollocationPattern]) VALUES (12, 2, 4, 3, 13, 5)
INSERT INTO [dbo].[Collocations] ([Id], [posId], [colPosId], [wordId], [colWordId], [CollocationPattern]) VALUES (13, 1, 2, 14, 15, 1)
INSERT INTO [dbo].[Collocations] ([Id], [posId], [colPosId], [wordId], [colWordId], [CollocationPattern]) VALUES (14, 1, 3, 16, 17, 2)
INSERT INTO [dbo].[Collocations] ([Id], [posId], [colPosId], [wordId], [colWordId], [CollocationPattern]) VALUES (15, 1, 9, 16, 19, 6)
INSERT INTO [dbo].[Collocations] ([Id], [posId], [colPosId], [wordId], [colWordId], [CollocationPattern]) VALUES (29, 1, 2, 51, 51, 1)
INSERT INTO [dbo].[Collocations] ([Id], [posId], [colPosId], [wordId], [colWordId], [CollocationPattern]) VALUES (39, 1, 2, 16, 14, 1)
INSERT INTO [dbo].[Collocations] ([Id], [posId], [colPosId], [wordId], [colWordId], [CollocationPattern]) VALUES (40, 1, 2, 2, 14, 1)
SET IDENTITY_INSERT [dbo].[Collocations] OFF
