SET IDENTITY_INSERT [dbo].[Words] ON
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (1, N'ability', N'能力', N'能力', N'能力', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (2, N'profile', N'展示', N'展示', N'プロファイルへ', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (3, N'abandon', N'放任; 放緃; 遺棄', N'放任; 放緃; 遗弃', N'フェア;耽溺;放棄', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (4, N'passionate', N'熱情的', N'热情的', N'情熱的な', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (5, N'appreciate', N'賞識', N'赏识', N'鑑賞する', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (6, N'hastily', N'倉促地', N'仓促地', N'急いで', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (7, N'altogether', N'共同', N'共同', N'完全に', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (8, N'natural', N'天然的', N'天然的', N'ナチュラル', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (9, N'demonstrate', N'顯露; 顯現', N'显露; 显现', N'実証する', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (10, N'lose', N'失去', N'失去', N'失う', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (11, N'effectively', N'事實上', N'事实上', N'効果的に', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (12, N'simply', N'根本上', N'根本上', N'単に', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (13, N'formally', N'正式地', N'正式地', N'正式に', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (14, N'look', N'看; 外觀', N'看; 外观', N'見える', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (15, N'wear', N'穿著', N'穿著', N'着用する', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (16, N'absence', N'缺席; 不在場', N'缺席; 不在场', N'不在', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (17, N'long', N'長的', N'长的', N'長い', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (18, N'period', N'期間', N'期间', N'期間', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (19, N'a/the period of ...', N'在...的期間', N'在...的期间', N'の...期間', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (35, N'To...', N'往...', N'往...', N'へ...', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (36, N'On behalf of...', N'代表...', N'代表...', N'の...代わっ', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (37, N'Upon...', N'在...之上', N'在...之上', N'で...トップ', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (39, N'In favor of...', N'為了...', N'为了...', N'為了...', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (40, N'For...', N'為了...', N'为了...', N'のため...', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (41, N'Under...', N'在...之下', N'在...之下', N'前の下...', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (42, N'Above...', N'在...之上', N'在...之上', N'で...トップ', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (43, N'In...', N'在...之內', N'在...之內', N'内...', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (44, N'At...', N'在...', N'在...', N'で...', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (45, N'On...', N'在...之上', N'在...之上', N'で...トップ', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (46, N'Of...', N'的...', N'的...', N'の...', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (47, N'From...', N'由...', N'由...', N'バイ...', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (48, N'Up...', N'往...上', N'往...上', N'行く...上', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (49, N'Down...', N'往...下', N'往...下', N'前の下...', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (50, N'Out of...', N'在...之外', N'在...之外', N'の...外', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (51, N'cheque', N'支票', N'支票', N'支票', 0)
INSERT INTO [dbo].[Words] ([Id], [Entry], [EntryZht], [EntryZhs], [EntryJap], [CanDel]) VALUES (60, N'cancel', N'取消', N'取消', N'取消', 1)
SET IDENTITY_INSERT [dbo].[Words] OFF
