INSERT INTO [dbo].[Prepositions] ([prepId], [Entry], [EntryChi], [EntryJap]) VALUES (N'p1', N'To...', N'往...', N'へ...')
INSERT INTO [dbo].[Prepositions] ([prepId], [Entry], [EntryChi], [EntryJap]) VALUES (N'p10', N'On behalf of...', N'代表...', N'の...代わっ')
INSERT INTO [dbo].[Prepositions] ([prepId], [Entry], [EntryChi], [EntryJap]) VALUES (N'p11', N'Upon...', N'在...之上', N'で...トップ')
INSERT INTO [dbo].[Prepositions] ([prepId], [Entry], [EntryChi], [EntryJap]) VALUES (N'p12', N'In favor of...', N'', N'')
INSERT INTO [dbo].[Prepositions] ([prepId], [Entry], [EntryChi], [EntryJap]) VALUES (N'p13', N'For...', N'為了...', N'のため...')
INSERT INTO [dbo].[Prepositions] ([prepId], [Entry], [EntryChi], [EntryJap]) VALUES (N'p14', N'Under...', N'在...之下', N'前の下...')
INSERT INTO [dbo].[Prepositions] ([prepId], [Entry], [EntryChi], [EntryJap]) VALUES (N'p15', N'Above...', N'在...之上', N'で...トップ')
INSERT INTO [dbo].[Prepositions] ([prepId], [Entry], [EntryChi], [EntryJap]) VALUES (N'p2', N'In...', N'在...之內', N'内...')
INSERT INTO [dbo].[Prepositions] ([prepId], [Entry], [EntryChi], [EntryJap]) VALUES (N'p3', N'At...', N'在...', N'で...')
INSERT INTO [dbo].[Prepositions] ([prepId], [Entry], [EntryChi], [EntryJap]) VALUES (N'p4', N'On...', N'在...之上', N'で...トップ')
INSERT INTO [dbo].[Prepositions] ([prepId], [Entry], [EntryChi], [EntryJap]) VALUES (N'p5', N'Of...', N'的...', N'の...')
INSERT INTO [dbo].[Prepositions] ([prepId], [Entry], [EntryChi], [EntryJap]) VALUES (N'p6', N'From...', N'由...', N'バイ...')
INSERT INTO [dbo].[Prepositions] ([prepId], [Entry], [EntryChi], [EntryJap]) VALUES (N'p7', N'Up...', N'往...上', N'行く...上')
INSERT INTO [dbo].[Prepositions] ([prepId], [Entry], [EntryChi], [EntryJap]) VALUES (N'p8', N'Down...', N'往...下', N'前の下...')
INSERT INTO [dbo].[Prepositions] ([prepId], [Entry], [EntryChi], [EntryJap]) VALUES (N'p9', N'Out of...', N'在...之外', N'の...外')
